### ISSUE TITLE
RestController only shown when add spring-boot-staret-web

### ISSUE THREAD

**Issue by rafaeldev** [AlexFalappa/nb-springboot#94]
Hi!

My project initialy have only 3 dependecies:
- spring-boot-starter-data-jpa
- spring-boot-starter-data-rest
- spring-boot-devtools

when I try create a RestController by Spring Framework panel the "RestController" options doesn't shown.

When I add `spring-boot-starer-web`, that option is show again.

This behavior is ok?
The `spring-boot-starter-data-rest` dependecy has `spring-boot-starer-web` how your dependecy. Would not that make the option appear?

Thanks.

**Comment by AlexFalappa** [comment]
@rafaeldev  showing the relevant file templates based on the actual project dependencies is by design, that is the plugin intentionally shows the _Rest Controller_ only if the project has the correct dependency.

However the current code detects only **direct** dependencies while, as you noticed, it should detect **indirect** (transitive) dependencies as well.
